#!/usr/bin/env python3

import os
import cgi
import cgitb

cgitb.enable()

print("Content-type: text/html\n")
print("<!DOCTYPE html>")
print("<html>")
print("<head>")
print("    <title>File Uploader</title>")
print("    <style>")
print("        body { font-family: Arial, sans-serif; text-align: center; margin: 50px; background-color: #f4f4f4; }")
print("        .container { max-width: 700px; margin: auto; background: white; padding: 20px; border-radius: 8px; box-shadow: 0 0 10px rgba(0,0,0,0.1); }")
print("        form { background: #f9f9f9; padding: 20px; border-radius: 5px; max-width: 500px; margin: auto; }")
print("        label { display: block; margin-bottom: 5px; font-weight: bold; }")
print("        input[type='text'] { width: 100%; padding: 10px; margin-bottom: 15px; border: 1px solid #ddd; border-radius: 4px; }")
print("        input[type='button'] { background-color: #4CAF50; color: white; padding: 10px 15px; border: none; border-radius: 4px; cursor: pointer; }")
print("        input[type='button']:hover { background-color: #45a049; }")
print("    </style>")
print("    <script>")
print("        function uploadFile() {")
print("            var filePath = document.getElementById('file_path').value.trim();")
print("            if (filePath) {")
print("                window.location.href = '/cgi-bin/upload.py/' + encodeURIComponent(filePath);")
print("            } else {")
print("                alert('Please enter a file path.');")
print("            }")
print("        }")
print("    </script>")
print("</head>")
print("<body>")
print("    <div class='container'>")
print("        <h1>Upload a File</h1>")
print("        <form onsubmit='event.preventDefault(); uploadFile();'>")
print("            <label for='file_path'>Enter absolute file path:</label>")
print("            <input type='text' id='file_path' name='file_path' placeholder='/Users/username/Desktop/example.txt' required>")
print("            <input type='button' value='Upload' onclick='uploadFile();'>")
print("        </form>")
print("    </div>")
print("</body>")
print("</html>")
