
server {
    listen 127.0.0.1:8080;
    server_name localhost;

    root ./www/html;
    index index.html;
    cgi_extension .php;
    
    error_page 404 404.html;
    client_max_body_size 1048576;
    autoindex on;

    location / {

    }
    
    location /uploads {
        upload_path /uploads;
        methods GET POST DELETE;
        autoindex off;
    }
    
    location /cgi-bin {
        methods GET POST;
        autoindex off;
    }
}

server {
    listen 8081;
    server_name mysite.com localhost;

    root ./www/html/mysite;
    index index.html;
    upload_path uploads;

    error_page 403 50x.html;
    error_page 500 50x.html;
    client_max_body_size 2097152;
    autoindex off;

    location / {
    }
    
    location /admin {
        methods GET POST DELETE;
        return 302 /login;
    }
}
