server {
    listen 8080;
    server_name localhost;

	root ./www/html;
    index index.html;
    client_max_body_size 1048576;
    autoindex on;
}

server {
    listen 8080;
    server_name A;

	root ./www/html;
    index 404.html;
}
server {
    listen 8080;
    server_name B;

	root ./www/html;
    index error/default_error.html;
}